#!/usr/bin/env python3

### Prenos baze NYSE v sqlite3

import sqlite3        # Knjižnica za delo z bazo
import csv            # Knjižnica za delo s CSV datotekami
import urllib.request # Knjižnica za delo s spletom
import re             # Knjižnica za delo z regularnimi izrazi

### Nastavitve

# Datoteka, v kateri je baza
BAZA = "prevoznistvo.sqlite"

### Program

### 1. NAREDIMO BAZO, ČE JE ŠE NIMAMO

# Naredimo povezavo z bazo. Funkcija sqlite3.connect vrne objekt,
# ki hrani podatke o povezavi z bazo.
baza = sqlite3.connect(BAZA)

# Naredimo tabelo delnica, če je še ni
baza.execute('''CREATE TABLE IF NOT EXISTS tovornjak (
  registrska TEXT PRIMARY KEY,
  nosilnost INTEGER NOT NULL,
  datum_rojstva DATE NOT NULL,
  ime TEXT NOT NULL,
  priimek TEXT NOT NULL)''')

# Naredimo tabelo promet, če je še ni
baza.execute('''CREATE TABLE IF NOT EXISTS mesta (
  id SERIAL PRIMARY KEY,
  ime TEXT,
  razdalja INTEGER)''')

baza.execute('''CREATE TABLE IF NOT EXISTS prevoz (
  id SERIAL PRIMARY KEY,
  datum DATE NOT NULL,
  kolicina INTEGER,
  cena_tone INTEGER,
  zacetek INTEGER REFERENCES mesta(id),
  konec INTEGER REFERENCES mesta(id))''')

baza.execute('''CREATE TABLE IF NOT EXISTS mesecni_stroski (
  registrska TEXT REFERENCES tovornjak(registrska),
  mesec TEXT,
  gorivo INTEGER,
  popravilo INTEGER,
  PRIMARY KEY(registrska, mesec))''')

baza.execute('''CREATE TABLE IF NOT EXISTS cestnina (
  registrska TEXT REFERENCES tovornjak(registrska),
  mesec TEXT NOT NULL,
  italija INTEGER CHECK(italija >= 0) DEFAULT 0,
  slovenija INTEGER CHECK(slovenija >= 0) DEFAULT 0,
  madzarska INTEGER CHECK(madzarska >= 0) DEFAULT 0,
  hrvaska INTEGER CHECK(hrvaska >= 0) DEFAULT 0,
  avstrija INTEGER CHECK(avstrija >= 0) DEFAULT 0,
  PRIMARY KEY(registrska, mesec))''')

baza.execute('''CREATE VIEW IF NOT EXISTS cestnina_na_mesec
AS SELECT
  SUM(italija) AS italjanska,
  SUM(slovenija) AS slovenska,
  SUM(madzarska) AS madzarska,
  SUM(hrvaska) AS hrvaska,
  SUM(avstrija) AS avstrijska
  FROM cestnina GROUP BY mesec''')

baza.execute('''CREATE VIEW IF NOT EXISTS cestnina_na_tovornjak
AS SELECT registrska,
  SUM(italija) AS italjanska,
  SUM(slovenija) AS slovenska,
  SUM(madzarska) AS madzarska,
  SUM(hrvaska) AS hrvaska,
  SUM(avstrija) AS avstrijska,
  SUM(italija) + SUM(slovenija) + SUM(madzarska) + SUM(hrvaska) + SUM(avstrija) AS skupaj
  FROM cestnina GROUP BY mesec, registrska''')

baza.execute('''CREATE VIEW IF NOT EXISTS stroski_na_tovornjak
AS SELECT
  SUM(gorivo) AS gorivo_na_mesec,
  SUM(skupaj) AS cestnina_na_mesec
  FROM mesecni_stroski JOIN cestnina_na_tovornjak ON mesecni_stroski.registrska = cestnina_na_tovornjak.registrska
  GROUP BY mesecni_stroski.registrska''')

# Obvezno moramo narediti commit, sicer se ne zgodi nič
baza.commit()


##INSERT V BAZO
baz="prevoznistvo.sqlite3"

baza=sqlite3.connect(baz)
baza.execute('''INSERT INTO tovornjak(registrska, nosilnost, datum_rojstva, ime, priimek) VALUES (?, ?, ?, ?, ?)''', ('123', 12, '21.2.2020', 'Lojze', 'Mejak'))
c=baza.cursor()
c.execute('''SELECT * FROM tovornjak''')
a=c.fetchone()
print(a)
baza.commit()

